title: Hacker theme
description: Hacker is a theme for GitHub Pages.
google_analytics:
theme: jekyll-theme-hacker
twitter: test
github: test
links:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Talks
    url: /talks
